name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t1
      id: t1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1
        setup-command: export HOME='/home/runner' && cd MyMath && dotnet restore
        command: export HOME='/home/runner' && cd MyMath && dotnet test | grep 5,
        timeout: 10
        max-score: 2
    - name: t2
      id: t2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t2
        setup-command: ''
        command: cat .github/workflows/publish_docs.yml | grep docfx
        timeout: 10
        max-score: 3
    - name: t3
      id: t3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t3
        setup-command: ''
        command: cat .github/workflows/publish_cov_report.yml | grep reportgenerator
        timeout: 10
        max-score: 3
    - name: t4
      id: t4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t4
        setup-command: ''
        command: cat .github/workflows/release.yml | grep nuget
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1_RESULTS: "${{steps.t1.outputs.result}}"
        T2_RESULTS: "${{steps.t2.outputs.result}}"
        T3_RESULTS: "${{steps.t3.outputs.result}}"
        T4_RESULTS: "${{steps.t4.outputs.result}}"
      with:
        runners: t1,t2,t3,t4
